### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by daniilmastrangeli** [tomasemilio/FastAPI-Boilerplate#13]
How come you decide to make querys inside the classes using classmethod? Instead of creating a repository?

**Comment by tomasemilio** [comment]
Hello. This is just a matter of preference. There are certain queries and logic that are pretty standard across models. As you can see I created a base class that functions as a parent for all the other models since i have id, created_at and updated_at.

There are other areas, such as the functions.py and dependencies.py, where i declare how i want to load an individual instance with its relationships. Just as a rule for this implementation, when i load more than one instance, I do not load relationships, but it is one according to id, then i load the relationships.

Again, this is a matter of preference and how you organize things. Personally, I don't love having too much logic inside the endpoint definition.
